#!/usr/bin/env node
/**
 * Git Hooks 安装脚本
 * 
 * @author 程序员
 * @date 2025-10-08
 * 
 * 功能：
 * 1. 安装pre-commit hook
 * 2. 安装post-commit hook
 * 3. 设置执行权限
 */

const fs = require('fs');
const path = require('path');

// 颜色输出
const colors = {
    reset: '\x1b[0m',
    red: '\x1b[31m',
    green: '\x1b[32m',
    yellow: '\x1b[33m',
    cyan: '\x1b[36m'
};

function log(message, color = 'reset') {
    console.log(`${colors[color]}${message}${colors.reset}`);
}

// 获取Git hooks目录
function getHooksDir() {
    const gitDir = path.join(process.cwd(), '.git');
    if (!fs.existsSync(gitDir)) {
        throw new Error('不是Git仓库');
    }
    return path.join(gitDir, 'hooks');
}

// 创建Hook文件
function createHook(hookName, scriptPath) {
    const hooksDir = getHooksDir();
    const hookPath = path.join(hooksDir, hookName);
    
    // Hook内容
    const hookContent = `#!/bin/sh
# Auto-generated by install-hooks.js
# Do not edit manually

node "${scriptPath}"
exit $?
`;
    
    try {
        // 写入文件
        fs.writeFileSync(hookPath, hookContent, { mode: 0o755 });
        log(`  ✅ ${hookName} 已安装`, 'green');
        return true;
    } catch (error) {
        log(`  ❌ ${hookName} 安装失败: ${error.message}`, 'red');
        return false;
    }
}

// 备份现有Hook
function backupHook(hookName) {
    const hooksDir = getHooksDir();
    const hookPath = path.join(hooksDir, hookName);
    
    if (fs.existsSync(hookPath)) {
        const backupPath = `${hookPath}.backup-${Date.now()}`;
        try {
            fs.copyFileSync(hookPath, backupPath);
            log(`  📦 已备份现有hook: ${path.basename(backupPath)}`, 'yellow');
            return true;
        } catch (error) {
            log(`  ⚠️  备份失败: ${error.message}`, 'yellow');
            return false;
        }
    }
    return true;
}

// 主函数
function main() {
    log('\n🔧 安装Git Hooks', 'cyan');
    log('═'.repeat(50), 'cyan');
    
    try {
        const hooksDir = getHooksDir();
        log(`\nHooks目录: ${hooksDir}`, 'cyan');
        
        // 确保hooks目录存在
        if (!fs.existsSync(hooksDir)) {
            fs.mkdirSync(hooksDir, { recursive: true });
        }
        
        // 安装hooks
        const hooks = [
            {
                name: 'pre-commit',
                script: path.join(__dirname, 'hooks', 'pre-commit.js')
            },
            {
                name: 'post-commit',
                script: path.join(__dirname, 'hooks', 'post-commit.js')
            }
        ];
        
        log('\n安装进度:', 'cyan');
        let success = 0;
        
        for (const hook of hooks) {
            // 检查脚本是否存在
            if (!fs.existsSync(hook.script)) {
                log(`  ❌ ${hook.name}: 脚本不存在 (${hook.script})`, 'red');
                continue;
            }
            
            // 备份现有hook
            backupHook(hook.name);
            
            // 创建hook
            if (createHook(hook.name, hook.script)) {
                success++;
            }
        }
        
        // 总结
        log('\n' + '═'.repeat(50), 'cyan');
        if (success === hooks.length) {
            log(`\n✅ 所有Hooks安装成功！(${success}/${hooks.length})`, 'green');
            log('\n现在提交代码时会自动执行审核。', 'cyan');
            log('使用 git commit --no-verify 可以跳过审核（不推荐）\n', 'yellow');
        } else {
            log(`\n⚠️  部分Hooks安装失败 (${success}/${hooks.length})`, 'yellow');
        }
        
    } catch (error) {
        log(`\n❌ 安装失败: ${error.message}\n`, 'red');
        process.exit(1);
    }
}

// 卸载函数
function uninstall() {
    log('\n🗑️  卸载Git Hooks', 'cyan');
    log('═'.repeat(50), 'cyan');
    
    try {
        const hooksDir = getHooksDir();
        const hooks = ['pre-commit', 'post-commit'];
        
        log('\n卸载进度:', 'cyan');
        let removed = 0;
        
        for (const hookName of hooks) {
            const hookPath = path.join(hooksDir, hookName);
            
            if (fs.existsSync(hookPath)) {
                // 检查是否是我们安装的
                const content = fs.readFileSync(hookPath, 'utf-8');
                if (content.includes('Auto-generated by install-hooks.js')) {
                    fs.unlinkSync(hookPath);
                    log(`  ✅ ${hookName} 已卸载`, 'green');
                    removed++;
                } else {
                    log(`  ⚠️  ${hookName} 不是由此脚本安装，跳过`, 'yellow');
                }
            } else {
                log(`  ℹ️  ${hookName} 不存在`, 'cyan');
            }
        }
        
        log('\n' + '═'.repeat(50), 'cyan');
        log(`\n✅ 卸载完成 (${removed}个)\n`, 'green');
        
    } catch (error) {
        log(`\n❌ 卸载失败: ${error.message}\n`, 'red');
        process.exit(1);
    }
}

// 命令行参数处理
const args = process.argv.slice(2);

if (args.includes('--uninstall') || args.includes('-u')) {
    uninstall();
} else if (args.includes('--help') || args.includes('-h')) {
    console.log(`
Git Hooks 安装工具

用法:
  node install-hooks.js          # 安装hooks
  node install-hooks.js -u       # 卸载hooks
  node install-hooks.js --help   # 显示帮助

说明:
  - 安装后，每次git commit都会自动执行审核
  - 使用 git commit --no-verify 可以跳过审核
  - 审核记录保存在 .git/commit-reviews/ 目录
    `);
} else {
    main();
}
